### ISSUE TITLE
How to flash firmware?

### ISSUE THREAD

**Issue by eviscerat** [solderparty/i2c_puppet#19]
How does one flashes the firmware after a build or the release files to the actual keyboard over usb?

**Comment by arturo182** [comment]
If you hold the top right key ("end call") while plugging the keyboard in over USB, it will enter BOOT mode and a removable drive RP2-BOOT will appear. Copy the uf2 file that was built over to that drive, the keyboard should reboot and will now be running the new firmware.

Let me know if there are any issues 👍

**Comment by eviscerat** [comment]
Thank you, I managed to flash a new firmware
