### ISSUE TITLE
Missing arrow keys

### ISSUE THREAD

**Issue by dglaude** [solderparty/i2c_puppet#6]
I did not find the proper way to navigate the cursor.
Maybe hjkl with a meta such as Fn could be used.
Vi user don't need arrows, but for nano or line editing, this is important.

**Comment by arturo182** [comment]
If you hold Alt down and swipe up/down/left/right on the trackpad, you get arrow keys. I think it's mentioned on the cheat sheet.

**Comment by dglaude** [comment]
Indeed, not super usable but it is there.
