### ISSUE TITLE
Missing original firmware UF2

### ISSUE THREAD

**Issue by dglaude** [solderparty/i2c_puppet#7]
In order to hack with the keyboard with a safe way to return to factory settings, you should provide the factory firmware as an artefact.

**Comment by arturo182** [comment]
That's fair. I want to add a workflow so each commit does a build and saves the artifact so also we can tag releases that way, will get on it soon.

**Comment by arturo182** [comment]
Workflow added, made a release

**Comment by dglaude** [comment]
Thanks, tested and it works for me.
